# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_qndNYXz-vNGLA-Xtvna34X7sBFdlWr
"""

import os
import shutil
import random

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

RAW_DECK_DIR = "/content/drive/MyDrive/sdnet2018/D"     # path to the folder containing CD and UD
DATASET_DIR = "dataset"
IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42
SPLIT = (0.8, 0.1, 0.1)          # train / val / test
CLASS_NAMES = None                # filled in after loading the dataset

random.seed(SEED)
tf.random.set_seed(SEED)

# STEP 1: Organize raw dataset into train/val/test folders (run once)

def organize_dataset():
    if os.path.exists(DATASET_DIR):
        print(f"'{DATASET_DIR}' already exists — skipping split.")
        return

    class_map = {"cracked": "CD", "non_cracked": "UD"}
    for split in ("train", "val", "test"):
        for cls in class_map:
            os.makedirs(os.path.join(DATASET_DIR, split, cls), exist_ok=True)

    for cls, raw_subdir in class_map.items():
        src_dir = os.path.join(RAW_DECK_DIR, raw_subdir)
        images = [f for f in os.listdir(src_dir) if f.lower().endswith((".jpg", ".jpeg", ".png"))]
        random.shuffle(images)

        n = len(images)
        n_train = int(n * SPLIT[0])
        n_val = int(n * SPLIT[1])
        splits = {
            "train": images[:n_train],
            "val": images[n_train:n_train + n_val],
            "test": images[n_train + n_val:],
        }
        for split, files in splits.items():
            dst_dir = os.path.join(DATASET_DIR, split, cls)
            for fname in files:
                shutil.copy(os.path.join(src_dir, fname), os.path.join(dst_dir, fname))
        print(f"{cls}: {n} images -> train={len(splits['train'])}, "
              f"val={len(splits['val'])}, test={len(splits['test'])}")

# STEP 2: Load datasets with image_dataset_from_directory (as in Lab 8)

def load_datasets():
    global CLASS_NAMES

    train_dataset = tf.keras.utils.image_dataset_from_directory(
        os.path.join(DATASET_DIR, "train"),
        image_size=IMAGE_SIZE,
        batch_size=BATCH_SIZE,
        label_mode="binary",
        seed=SEED,
    )
    val_dataset = tf.keras.utils.image_dataset_from_directory(
        os.path.join(DATASET_DIR, "val"),
        image_size=IMAGE_SIZE,
        batch_size=BATCH_SIZE,
        label_mode="binary",
        seed=SEED,
    )
    test_dataset = tf.keras.utils.image_dataset_from_directory(
        os.path.join(DATASET_DIR, "test"),
        image_size=IMAGE_SIZE,
        batch_size=BATCH_SIZE,
        label_mode="binary",
        seed=SEED,
    )

    CLASS_NAMES = train_dataset.class_names  # ['cracked', 'non_cracked']
    print("Class names:", CLASS_NAMES)

    AUTOTUNE = tf.data.AUTOTUNE
    train_dataset = train_dataset.prefetch(AUTOTUNE)
    val_dataset = val_dataset.prefetch(AUTOTUNE)
    test_dataset = test_dataset.prefetch(AUTOTUNE)
    return train_dataset, val_dataset, test_dataset

# STEP 3: Data augmentation (as in Lab 8)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.2),
    tf.keras.layers.RandomZoom(0.2),
])

# STEP 4: Custom CNN architecture (same block pattern as Lab 8)

def build_custom_cnn(input_shape):
    inputs = tf.keras.Input(shape=input_shape)
    x = data_augmentation(inputs)
    x = tf.keras.layers.Rescaling(1.0 / 255)(x)

    x = tf.keras.layers.Conv2D(32, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Conv2D(32, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D()(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(64, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Conv2D(64, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D()(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(128, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Conv2D(128, 3, padding="same", activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D()(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(256, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    # Binary task -> 1 sigmoid unit (Lab 8 used softmax for multi-class;
    # for cracked vs non-cracked we use sigmoid + binary_crossentropy)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    return tf.keras.Model(inputs, outputs, name="custom_cnn")

# STEP 5: Transfer learning with MobileNetV3Small (as in Lab 8)

def build_transfer_model(input_shape):
    base_model = tf.keras.applications.MobileNetV3Small(
        input_shape=input_shape,
        include_top=False,
        weights="imagenet",
    )
    base_model.trainable = False
    preprocess_fn = tf.keras.applications.mobilenet_v3.preprocess_input

    inputs = tf.keras.Input(shape=input_shape)
    x = data_augmentation(inputs)
    x = preprocess_fn(x)
    x = base_model(x, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(256, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.2)(x)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    return tf.keras.Model(inputs, outputs, name="mobilenetv3_transfer"), base_model

# STEP 6: Callbacks (same as Lab 8)

def get_callbacks(name):
    os.makedirs("models", exist_ok=True)
    return [
        tf.keras.callbacks.ModelCheckpoint(
            filepath=f"models/{name}_best.keras",
            monitor="val_accuracy", save_best_only=True,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=5, restore_best_weights=True,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=3,
        ),
    ]

# STEP 7: Train, evaluate, and save both models

def main():
    organize_dataset()
    train_dataset, val_dataset, test_dataset = load_datasets()
    input_shape = IMAGE_SIZE + (3,)

    # Custom CNN
    print("\n=== Training Custom CNN ===")
    cnn_model = build_custom_cnn(input_shape)
    cnn_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    cnn_model.fit(
        train_dataset, validation_data=val_dataset, epochs=25,
        callbacks=get_callbacks("custom_cnn"),
    )

    # Transfer Learning (MobileNetV3Small)
    print("\n=== Training MobileNetV3 Transfer Learning Model ===")
    tl_model, base_model = build_transfer_model(input_shape)
    tl_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    tl_model.fit(
        train_dataset, validation_data=val_dataset, epochs=10,
        callbacks=get_callbacks("mobilenetv3_transfer"),
    )

    print("\n=== Fine-tuning MobileNetV3 ===")
    base_model.trainable = True
    fine_tune_at = len(base_model.layers) - 30
    for layer in base_model.layers[:fine_tune_at]:
        layer.trainable = False

    tl_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    tl_model.fit(
        train_dataset, validation_data=val_dataset, epochs=5,
        callbacks=get_callbacks("mobilenetv3_finetuned"),
    )

    # Evaluate both models on the test set
    print("\n=== Evaluation on Test Set ===")
    cnn_loss, cnn_acc = cnn_model.evaluate(test_dataset)
    tl_loss, tl_acc = tl_model.evaluate(test_dataset)
    print(f"Custom CNN         -> Test Accuracy: {cnn_acc:.4f}, Loss: {cnn_loss:.4f}")
    print(f"MobileNetV3 (TL)   -> Test Accuracy: {tl_acc:.4f}, Loss: {tl_loss:.4f}")

    # Save both trained models
    os.makedirs("models", exist_ok=True)
    cnn_model.save("models/custom_cnn.keras")
    tl_model.save("models/mobilenetv3_transfer.keras")
    print("\nModels saved:")
    print("  models/custom_cnn.keras")
    print("  models/mobilenetv3_transfer.keras")
    print("\nUse whichever model scored higher test accuracy in app.py.")


if __name__ == "__main__":
    main()